export default {

    addNewOrgBtnDropdown: ".vs-c-list__btn > svg",
    addOrganizationBtn:".vs-c-tooltip-active-sprints .vs-c-list > li",
    inputNameOrg: "input[type='text']",
    nextBtn: "button[name='next_btn']",
    cancelBtn: "button[name='prev_btn']",
    closeBtn: "button[name='close-new-board-modal-btn']",
    createBtn: "button[name='next_btn']", 
    previousBtn: "button[name='prev_btn']",
    clickOrg: ".vs-c-list__btn",
    clickConfig: "[class='vs-l-project__menu'] > ul > li",
    deleteOrg: "button > span",
    changeOrgName:"[class='el-tooltip__popper is-dark']" ,
    checkEditedOrg: "i[class='el-icon-check']",
    confirmPassDeleteOrg: "input[type='password']",
    saveConfirmBtn: "button[name='save-btn']",
    noticeOkClose: ".vs-c-modal--features-button > .vs-c-btn",
    arhiveOrgBtn : "button[class='vs-c-btn vs-c-btn--success vs-c-btn--spaced']",
    orgFromArhived: "[class='vs-c-my-organization organization-list-item']",
    deleteArhivedOrg: ".vs-c-icon--remove",
    infoBoardOk: "[class='vs-c-btn vs-c-btn--primary vs-c-btn--lg vs-u-font-sm vs-c-modal--features-confirm-button']",
    configBtnSubmit: "button[type='submit']",
    listOrg: ".vs-l-my-organizations__content",
    nameOrg: "input[data-vv-as='name']",
    deleteOrgBtn: "button[class='vs-c-btn vs-c-btn--warning vs-c-btn--spaced vs-u-gap--left']",
    editOrg: "span[title='Edit Organization']",
    editOrgName: "[name='change-organization-name']"
}